atok/atok/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feed/', include('feed.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

atok/feed/urls.py
from django.conf.urls import url

from . import views

app_name = 'feed'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^user/(?P<pk>[0-9]+)/$', views.profile, name='profile'),
 	url(r'^user/(?P<pk>[0-9]+)/feed/$', views.index_user, name='index_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<update_id>[0-9]+)/verify/$', views.verify, name='verify'),
    url(r'^update/$', views.post_update, name='post'),
]

atok/feed/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.
class Update(models.Model):
	update_text = models.CharField(max_length=10)
	user = models.ForeignKey(User)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.update_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
		
class Verify(models.Model):
	update = models.ForeignKey(Update, on_delete=models.CASCADE)
	level = models.CharField(max_length=10)
	affirmations = models.IntegerField(default=0)
	def __str__(self):
		return self.level

atok/feed/forms.py
from django import forms

from .models import Update, Verify

class UpdateForm(forms.Form):
	Choices = (
		('Stable', 'Unstable', 'Emergency', 'Unknown'),
	)
	update_status = forms.ChoiceField(choices=Choices, required=True, label='Current Status')

atok/feed/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required


from .models import Update, Verify
from .forms import UpdateForm

# Create your views here.
class IndexView(generic.ListView):
	template_name = 'feed/index.html'
	context_object_name = 'latest_update_list'
	
	def get_queryset(self):
		return Update.objects.order_by('-pub_date')[:5]
	
class DetailView(generic.DetailView):
    model = Update
    template_name = 'feed/detail.html'
    
def verify(request, update_id):
	update = get_object_or_404(Update, pk=update_id)
	try:
		selected_verify = update.verify_set.get(pk=request.POST['verify'])
	except (KeyError, Verify.DoesNotExist):
		return render(request, 'feed/verify.html', {
			'update': update,
			'error_message': "Please select a level.",
		})
	else:
		selected_verify.affirmations += 1
		selected_verify.save()
		return HttpResponseRedirect(reverse('feed:detail', args=(update.id,)))
	
def profile(request, pk):
	user = User.objects.filter(pk=pk)
	return render(request, 'feed/profile.html', {'user': user})

def index_user(request, username):
    updates = Update.objects.filter(user__username__iexact=username)
    return render(request, 'feed/index.html', {
        'updates': updates,
        'reason': "Viewing all of {}'s updates".format(username)
    })

@login_required
def post_update(request):
	if request.method == 'POST':
		form = UpdateForm(request.POST)
		if form.is_valid():
			return render(request, 'feed:detail')
	else:
		form = UpdateForm()
	
	return render(request, 'feed/create.html', {'form': form})
		
		
		
		
		
		
		
		
		
		
		

atok/feed/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
	<link href='https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'feed/style.css' %}" />
</head>
<body>
<ul class="nav">
        <li><h1>Are They OK?</h1></li>
        <li><a href="{% url 'feed:index' %}">Home</a></li>
        <li><a >Networks</a></li>
    </ul>
</body>

atok/feed/templates/feed/base.html
{% load staticfiles %}
{% load helpers %}

<!doctype html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Marvel search{% endblock %}</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'listing/pure-min.css' %}">
  <link rel="stylesheet" href="{% static 'listing/style.css' %}">
  <script type="text/javascript">
    !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
      analytics.load("3enenuYhPPK1EYPVGdQaE0LDf6bsDrDE");
      analytics.page()
    }}();
    {% block head %}{% endblock %}
  </script>
</head>
<body>
<div class="page">
  <div class="pagetitle">
    <div class="pure-menu pure-menu-horizontal">
      <a class="logo pure-menu-heading pure-menu-link" href="/">
        <img style="max-height:0.7em" src="{% static 'listing/nightcrawler.png' %}"/>
        Nightcrawler
      </a>
      {% with request.resolver_match.view_name as url %}
        <ul class="nav pure-menu-list">
          <li class="pure-menu-item {{ url|active_link:'listing:listing' }}"><a href="{% url 'listing:listing' %}" class="pure-menu-link">comics</a></li>
          <li class="pure-menu-item {{ url|active_link:'listing:synced' }}"><a href="{% url 'listing:synced' %}" class="pure-menu-link">synced</a></li>
          <li class="pure-menu-item {{ url|active_link:'listing:creators' }}"><a href="{% url 'listing:creators' %}" class="pure-menu-link">creators</a></li>
          <li class="pure-menu-item {{ url|active_link:'listing:search' }}"><a href="{% url 'listing:search' %}" class="pure-menu-link">search</a></li>
          {% if not request.user.is_authenticated %}
            <li class="pure-menu-item"><a href="{% url 'account_login' %}" class="pure-menu-link">login</a></li>
            <li class="pure-menu-item"><a href="{% url 'account_signup' %}" class="pure-menu-link">signup</a></li>
          {% else %}
            <li class="pure-menu-item"><a href="{% url 'extras:profile' request.user.id %}" class="pure-menu-link">profile</a></li>
            <li class="pure-menu-item"><a href="{% url 'account_logout' %}" class="pure-menu-link">logout</a></li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </div>
  {% if messages %}
    <div class="messages">
      {% for message in messages %}
        <div{% if message.tags %} class="message {{ message.tags }}"{% endif %}>{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}
  {% block content %}{% endblock %}
</div>
{% block script %}{% endblock %}
{#<script src="{% static 'listing/pure.js' %}"></script>#}
</body>

atok/feed/templates/feed/create.html
{% block title %}Post Update{% endblock %}

{% block content %}
	<h1>Post Update</h1>
	<form action="update-status" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

atok/feed/templates/feed/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'feed/style.css' %}" />
<h1>{{ update.user }} is {{ update.update_text }}</h1>

<ul>
{% for verify in update.verify_set.all %}
    <li>{{ verify.level }} -- {{ verify.affirmations }} affirmation{{ verify.affirmations|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'feed:verify' update.id %}">Verify</a>

atok/feed/templates/feed/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'feed/style.css' %}" />

{% if latest_update_list %}
	<ul>
	{% for update in latest_update_list %}
		<li><a href="{% url 'feed:detail' update.id %}">{{ update.user }} is {{ update.update_text }}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>No updates to view.</p>
{% endif %}

atok/feed/templates/feed/post.html
<form action="/Update/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

atok/feed/templates/feed/profile.html
{% block content %}
  <h1>{{ user.username }}'s Profile</h1>
  
{% endblock %}

atok/feed/templates/feed/verify.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'feed/style.css' %}" />
<h1>{{ update.user }} is {{ update.update_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'feed:verify' update.id %}" method="post">
{% csrf_token %}
{% for verify in update.verify_set.all %}
	<input type="radio" name="verify" id="verify{{ forloop.counter }}" value="{{verify.id }}" />
	<label for="verify{{ forloop.counter }}">{{ verify.level }}</label>
<br />
{% endfor %}
<input type="submit" value="Verify" />
</form>